version: '2'
services:
  pipe_vms_chile:
    image: "gfw/pipe-vms-chile"
    build: .
    volumes:
      - ".:/opt/project"
      - "gcp:/root/.config/"

  gcloud:
    image: "gfw/pipe-vms-chile"
    build: .
    entrypoint: gcloud
    volumes:
      - "gcp:/root/.config/"

  test:
    image: "gfw/pipe-vms-chile"
    build: .
    entrypoint: py.test
    volumes:
      - ".:/opt/project"
      - "gcp:/root/.config/"

# Use an external named volume so that we can share gcp auth across containers
# Before first use, this volume must be manually created with
#   docker volume create --name=gcp
volumes:
  gcp:
    external: true
